[project]
name = "quiet-route"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Peter Ehrlich", email = "55223557+pehrlich2@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "ortools>=9.15.6755",
    "osmnx>=2.1.1",
    "scipy>=1.18.1",
]

[project.scripts]
quiet-route = "quiet_route:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
